<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>solisp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>[\(\{]</string>
	<key>foldingStopMarker</key>
	<string>[\)\}]</string>
	<key>name</key>
	<string>Solisp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.solisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number_sign.solisp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.solisp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.solisp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.solisp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.solisp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Set|Mutate|MapI?)\b\s+((\w)*)\b</string>
			<key>name</key>
			<string>support.function.solisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(If|Switch)\b</string>
			<key>name</key>
			<string>keyword.control.solisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(((\B\-)?\b[0-9]+)\b)|(\b(True|False)\b)</string>
			<key>name</key>
			<string>constant.numeric.solisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\B[\+\-*/%]\B</string>
			<key>name</key>
			<string>keyword.operator.arithmtic.solisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\B(==|!=|>=|&lt;=|[>&lt;])\B</string>
			<key>name</key>
			<string>keyword.operator.comparison.solisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[NBRDHCS][01]?[0-9]\b</string>
			<key>name</key>
			<string>constant.numeric.cardsolisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Standard|this|Start-Extra|GOAL|INPUT|OUTPUT|HIDDEN|BUTTON|MIRRORED|MULTI|CUSTOM)\b</string>
			<key>name</key>
			<string>constant.other.cardsolisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Apply|On-(Grab|Place|Start)|(Grab|Place)-If)\b</string>
			<key>name</key>
			<string>keyword.control.cardsolisp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(VLayout|HLayout|VStack|HStack|PStack|Slot)\b</string>
			<key>name</key>
			<string>storage.type.function.cardsolisp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.solisp</string>
</dict>
</plist>