.TH Solisp 1
.SH NAME
solisp \- interpreter for a lisp-based programming language
.SH SYNOPSIS
.B solisp [\fIfile\fR]
.SH DESCRIPTION
.B solisp
Solisp is a small interpreted programming language based off of a lisp syntax.
This interpreter can either display an interactive prompt expierience or it can run a provided file.